name: AntiLeakAccount
version: ${project.version}
main: cn.mcres.luckyfish.antileakaccount.AntiLeakAccount
api-version: 1.16
authors: [Lucky_fish20]
description: Check if the premium account is legal

commands:
  alawhitelist:
    aliases:
      - awhitelist
      - awl
    permission: antileakaccount.whitelist
  alareload:
    permission: antileakaccount.reload

permissions:
  antileakaccount.reload:
    default: op
  antileakaccount.whitelist:
    default: op
    children:
      antileakaccount.whitelist.add: true
      antileakaccount.whitelist.remove: true
      antileakaccount.whitelist.list: true
      antileakaccount.whitelist.import: true
  antileakaccount.whitelist.add:
    default: op
  antileakaccount.whitelist.remove:
    default: op
  antileakaccount.whitelist.list:
    default: op
  antileakaccount.whitelist.import:
    default: op
  antileakaccount.verify:
    default: true
